---
applications:
- name: simple-boot-app
  instances: 1
  memory: 1G
  path: "../target/simple-boot-app.jar"
  env:
      SPRING_PROFILES_ACTIVE : dev 
  instances: 1
  memory: 1G
  routes:
    - route: simple-boot-app.cfapps.io
