---
applications:
- name: simple-boot-app
  instances: 1
  memory: 1G
  buildpack: java_buildpack
  path: "../target/simple-boot-app.jar"
  env:
      SPRING_PROFILES_ACTIVE : prod 
  instances: 1
  memory: 1G
  routes:
    - route: simple-boot-app.snm-prod.io
